# Generated by Django 5.2.7 on 2025-12-14 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_subcategory_priority_alter_subcategory_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='faculty',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='complaints.category'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='complaints.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='faculty',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
