# Generated by Django 5.2.7 on 2026-01-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_category_faculty_alter_complaint_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(),
        ),
    ]
