# Generated by Django 5.2.7 on 2025-10-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0004_category_locationstate_userprofile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="state",
        ),
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="category",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="subcategory",
        ),
        migrations.DeleteModel(
            name="LocationState",
        ),
        migrations.DeleteModel(
            name="SubCategory",
        ),
    ]
