# Generated by Django 5.1.13 on 2025-11-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0005_remove_complaint_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(
                blank=True, help_text="Age must be at least 15", null=True
            ),
        ),
    ]
