# Generated by Django 5.1.13 on 2025-11-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0006_userprofile_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="category",
        ),
        migrations.RemoveField(
            model_name="facultyprofile",
            name="department",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="department",
        ),
        migrations.RemoveField(
            model_name="facultyprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="priority",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="FacultyProfile",
        ),
        migrations.DeleteModel(
            name="StudentProfile",
        ),
    ]
