# Generated by Django 5.1.14 on 2025-11-11 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0007_remove_complaint_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="category",
            field=models.CharField(
                choices=[
                    ("academic", "Academic Issues"),
                    ("disciplinary", "Disciplinary / Conduct Issues"),
                    ("hostel", "Hostel / Accommodation Issues"),
                    ("mess", "Mess / Food Quality"),
                    ("transport", "Transport / Bus Facility"),
                    ("library", "Library & Study Resources"),
                    ("lab", "Lab / Equipment Issues"),
                    ("maintenance", "Campus Maintenance"),
                    ("it", "IT / Internet / Login Issues"),
                    ("administration", "Administrative / Documentation"),
                    ("finance", "Fees / Accounts / Scholarship"),
                    ("security", "Safety / Security"),
                ],
                db_index=True,
                default="administration",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("academic", "Academic Issues"),
                    ("disciplinary", "Disciplinary / Conduct Issues"),
                    ("hostel", "Hostel / Accommodation Issues"),
                    ("mess", "Mess / Food Quality"),
                    ("transport", "Transport / Bus Facility"),
                    ("library", "Library & Study Resources"),
                    ("lab", "Lab / Equipment Issues"),
                    ("maintenance", "Campus Maintenance"),
                    ("it", "IT / Internet / Login Issues"),
                    ("administration", "Administrative / Documentation"),
                    ("finance", "Fees / Accounts / Scholarship"),
                    ("security", "Safety / Security"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["category"], name="complaints__categor_8115a1_idx"
            ),
        ),
    ]
