# Generated by Django 5.1.13 on 2025-11-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0009_alter_complaint_assigned_to_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("RESOLVED", "Resolved"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
